import { Dimensions, Platform, StyleSheet } from 'react-native';

const mobilestyles = {};

const { width } = Dimensions.get('window');
const isWeb = width > 800;
const webstyles = {
  scrollContainer: {
    maxHeight: '50vh', 
    borderRadius: 10,
    backgroundColor: '#fff',
    margin: 20,
    overflow: 'hidden',
    marginLeft: '-2vw',
    marginTop: '1vw',
    borderWidth: 2.34,
    borderColor: '#a2a2a2dd',
  },
 
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10.5,
    paddingHorizontal: 10,
  },
  rowEven: {
    backgroundColor: '#d5d5d555',
  },
  rowOdd: {
    backgroundColor: 'white',
  },
  headerRow: {
    backgroundColor: '#52b1ffff',
    paddingVertical: 14,
    height: '8vh',
    borderColor: 'lightgrey',
    borderBottomColor: '#a2a2a2dd',
    borderBottomWidth: 2,
  },
  headcolSerial: {
    fontSize: '1.4vw',
    flex: 1,
    fontWeight: '600',
    color: '#000',
    textAlign: 'center',
  },
   headcolName: {
    fontSize: '1.4vw',
    flex: 1,
    fontWeight: '600',
    color: '#000',
    textAlign: 'center',
  },
   headcolEmail: {
    fontSize: '1.4vw',
    flex: 1.5,
    fontWeight: '600',
    color: '#000',
    textAlign: 'center',
  },
   headcolNumber: {
    fontSize: '1.4vw',
    flex: 1,
    fontWeight: '600',
    color: '#000',
    textAlign: 'center',
  },
   headcolRole: {
    fontSize: '1.4vw',
    flex: 1,
    fontWeight: '600',
    color: '#000',
    textAlign: 'center',
  },
  headcolStatus: {
    fontSize: '1.4vw',
    flex: 1,
    fontWeight: '600',
    color: '#000',
    textAlign: 'center',
  },
  headcolActions: {
    fontSize: '1.4vw',
    flex: 1,
    fontWeight: '600',
    textAlign: 'center',
  },
  colSerial: {
    fontSize: '1.2vw',
    flex: 1,
    fontWeight: '500',
    color: '#000',
    textAlign: 'center',
  },
  colName: {
    fontSize: '1.1vw',
    flex: 1,
    fontWeight: '500',
    color: '#000',
    textAlign: 'center',
  },
  colEmail: {
    fontSize: '1.1vw',
    flex: 1.5,
    fontWeight: '500',
    color: '#000',
    textAlign: 'center',
  },
  colNumber: {
    fontSize: '1.1vw',
    flex: 1,
    fontWeight: '500',
    color: '#000',
    textAlign: 'center',
  },
 colRole: {
  fontSize: '1.1vw',
  flex: 1,
  fontWeight: '500',
  color: '#000',
  textAlign: 'center',
  },
  colActions: {
    flex: 1,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center', 
  alignItems: 'center',     
  },
  actionicon: {
    marginHorizontal: 4,
    width: '3vw',
    height: '3vh',
  },
  picker: {
  fontSize: '1.1vw',
  height: 40,
  width: 155,
  fontWeight: '500',
  backgroundColor: 'transparent',
  color: '#000',
  paddingRight: '1vw',
  borderWidth: 0,
  borderRadius: 5,
 },
 search: {
    flexDirection: 'row',
    marginTop: '3vw',
    marginBottom: '1vw',
    marginLeft: '0.5vw',
 },
 searchtext: {
  fontSize: '1.3vw',
    fontWeight: '600',
    color: '#000',
    textAlign: 'center',
    justifyContent: 'center',
    backgroundColor: 'lightgrey',
    width: '5vw',
    paddingTop: 3,
    borderWidth: 1.5,
    borderColor: 'lightgrey',
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
    marginLeft: '-2vw',
    borderColor: 'grey',
 },
searchbutton: {
  height: '2.5vw',
  width: '3vw',
  backgroundColor: 'lightgrey',
  alignItems: 'center',
  justifyContent: 'center',
  borderColor: 'grey',
  borderWidth: 1.5,
},

searchicon: {
  width: '75%',
  height: '75%',
},
  cleartext: {
    fontSize: '1.3vw',
    fontWeight: '500',
    color: '#000',
    paddingTop: 3,
    height: '2.49vw',
    width: '5vw',
    backgroundColor: 'lightgrey',
    textAlign: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'grey',
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
 },
 input: {
  flex: 0.5,
    backgroundColor: 'white',
    padding: 7,
    paddingBottom: 5,
    height: '2.5vw',
    fontSize: '1.3vw',
    width: '25vw',
    borderWidth: 1.5,
    borderColor: 'grey',
    color: 'black',
    placeholderTextColor: 'grey',
  },
};

const styles = Platform.OS === 'web' ? webstyles : mobilestyles;

export default StyleSheet.create(styles);
